In [6]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

Given the following confusion matrix, evaluate (by hand) the model's performance.


|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |

In [52]:
TP = 46
TN = 34
FP = 13
FN = 7

accuracy = (TP + TN) / (TP + TN + FP + FN)
accuracy

0.8

In the context of this problem, what is a false positive?

In [ ]:
The model predicted dog but the actual value was cat.

In the context of this problem, what is a false negative?

In [ ]:
The model predicted cat but the actual value was dog.

How would you describe this model?

This model is more accurate than baseline.

baseline = (TP + FN) / (TP + TN + FP + FN) = 0.53

In [39]:
df = pd.read_csv('c3.csv')
df.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

Use the predictions dataset and pandas to help answer the following questions:

An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   actual  200 non-null    object
 1   model1  200 non-null    object
 2   model2  200 non-null    object
 3   model3  200 non-null    object
dtypes: object(4)
memory usage: 6.4+ KB


In [40]:
df.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [46]:
confusion_matrix(df.actual, df.model1,
                 labels = ('Defect', 'No Defect'))

array([[  8,   8],
       [  2, 182]])

In [47]:
confusion_matrix(df.actual, df.model2,
                 labels = ('Defect', 'No Defect'))


array([[  9,   7],
       [ 81, 103]])

In [48]:
confusion_matrix(df.actual, df.model3,
                 labels = ('Defect', 'No Defect'))

array([[13,  3],
       [86, 98]])

- Use recall to find out if the model does well at capturing true positives

- TP / (TP + FN)

In [49]:
from sklearn.metrics import classification_report
pd.DataFrame(classification_report(df.actual, df.model1, output_dict=True))

Defect   No Defect  accuracy   macro avg  weighted avg
precision   0.800000    0.957895      0.95    0.878947      0.945263
recall      0.500000    0.989130      0.95    0.744565      0.950000
f1-score    0.615385    0.973262      0.95    0.794323      0.944632
support    16.000000  184.000000      0.95  200.000000    200.000000

In [50]:
pd.DataFrame(classification_report(df.actual, df.model2, output_dict=True))

Defect   No Defect  accuracy   macro avg  weighted avg
precision   0.100000    0.936364      0.56    0.518182      0.869455
recall      0.562500    0.559783      0.56    0.561141      0.560000
f1-score    0.169811    0.700680      0.56    0.435246      0.658211
support    16.000000  184.000000      0.56  200.000000    200.000000

In [51]:
pd.DataFrame(classification_report(df.actual, df.model3, output_dict=True))

Defect   No Defect  accuracy   macro avg  weighted avg
precision   0.131313    0.970297     0.555    0.550805      0.903178
recall      0.812500    0.532609     0.555    0.672554      0.555000
f1-score    0.226087    0.687719     0.555    0.456903      0.650789
support    16.000000  184.000000     0.555  200.000000    200.000000

- Model 3 would be the best model for predicting the largest number of defects.

Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you they really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

- Specificity would be the most effective metric to capture the most true negatives. 

- TN / (TN + FP)

- Model 1 would be the best model for having the least number of false positives.

You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

Several models have already been developed with the data, and you can find their results here.

Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

In [56]:
paws = pd.read_csv('gives_you_paws.csv')
paws.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [62]:
paws.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [64]:
3254 / 5000 # baseline

0.6508

In [57]:
pd.crosstab(paws.actual, paws.model1)

model1   cat   dog
actual            
cat     1423   323
dog      640  2614

In [58]:
pd.crosstab(paws.actual, paws.model2)

model2   cat   dog
actual            
cat     1555   191
dog     1657  1597

In [59]:
pd.crosstab(paws.actual, paws.model3)

model3   cat   dog
actual            
cat      893   853
dog     1599  1655

In [61]:
pd.crosstab(paws.actual, paws.model4)

model4  cat   dog
actual           
cat     603  1143
dog     144  3110

In [65]:
pd.DataFrame(classification_report(paws.actual, paws.model1, output_dict=True))

cat          dog  accuracy    macro avg  weighted avg
precision     0.689772     0.890024    0.8074     0.789898      0.820096
recall        0.815006     0.803319    0.8074     0.809162      0.807400
f1-score      0.747178     0.844452    0.8074     0.795815      0.810484
support    1746.000000  3254.000000    0.8074  5000.000000   5000.000000

In [66]:
pd.DataFrame(classification_report(paws.actual, paws.model2, output_dict=True))

cat          dog  accuracy    macro avg  weighted avg
precision     0.484122     0.893177    0.6304     0.688649      0.750335
recall        0.890607     0.490781    0.6304     0.690694      0.630400
f1-score      0.627269     0.633479    0.6304     0.630374      0.631310
support    1746.000000  3254.000000    0.6304  5000.000000   5000.000000

In [67]:
pd.DataFrame(classification_report(paws.actual, paws.model3, output_dict=True))

cat          dog  accuracy    macro avg  weighted avg
precision     0.358347     0.659888    0.5096     0.509118      0.554590
recall        0.511455     0.508605    0.5096     0.510030      0.509600
f1-score      0.421425     0.574453    0.5096     0.497939      0.521016
support    1746.000000  3254.000000    0.5096  5000.000000   5000.000000

In [68]:
pd.DataFrame(classification_report(paws.actual, paws.model4, output_dict=True))

cat          dog  accuracy    macro avg  weighted avg
precision     0.807229     0.731249    0.7426     0.769239      0.757781
recall        0.345361     0.955747    0.7426     0.650554      0.742600
f1-score      0.483755     0.828560    0.7426     0.656157      0.708154
support    1746.000000  3254.000000    0.7426  5000.000000   5000.000000

Models 1 and 4 are better than baseline. Model 1 has the highest accuracy overall at 80.7 percent. Model 2 is slightly less accurate than baseline at 63 percent, model 3 is less than baseline at 51 percent, and model 4 has 74 percent accuracy.

Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?

- Model 2 has the best precision for dog pictures at 89.3 percent.

Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?

- Model 4 has the best precision for cat pictures at 80.7 percent.

Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

sklearn.metrics.accuracy_score

sklearn.metrics.precision_score

sklearn.metrics.recall_score

sklearn.metrics.classification_report

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(paws.actual, paws.model1)

0.8074

In [78]:
from sklearn.metrics import precision_score
precision_score(paws.actual, paws.model2, pos_label='dog')

0.8931767337807607

In [79]:
precision_score(paws.actual, paws.model2, pos_label='cat')

0.4841220423412204

In [81]:
from sklearn.metrics import recall_score
recall_score(paws.actual, paws.model3, pos_label='dog')

0.5086047940995697

In [82]:
recall_score(paws.actual, paws.model3, pos_label='cat')

0.5114547537227949

In [85]:
print(classification_report(paws.actual, paws.model4))

              precision    recall  f1-score   support

         cat       0.81      0.35      0.48      1746
         dog       0.73      0.96      0.83      3254

    accuracy                           0.74      5000
   macro avg       0.77      0.65      0.66      5000
weighted avg       0.76      0.74      0.71      5000

